name: Build and Deploy

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Jekyll
        run: |
          gem install --user-install jekyll
          echo "/home/runner/.local/share/gem/ruby/3.2.0/bin" >> $GITHUB_PATH

      - name: Build the site
        run: jekyll build

      - name: Test the site
        run: docker run --rm -v "$PWD:/srv/jekyll" -it jekyll/jekyll jekyll doctor

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

      - name: Deploy to GitHub Pages (Test Branch)
        if: github.ref == 'refs/heads/test'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages-test
